# Generated by Django 4.0.2 on 2023-02-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_profile_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowersCount',
            new_name='Followers',
        ),
    ]
